services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/opt/jacobianmatthews.com/frontend
    environment:
      PORT: 3000
      FIREBASE_EMULATORS: 'true'
      BACKEND_URL: http://backend:3001
    ports:
      - 3000:3000
    depends_on:
      - backend
  
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend:/opt/jacobianmatthews.com/backend
    environment:
      PORT: 3001
      FIREBASE_EMULATORS: 'true'
    ports:
      - 3001:3001

  emulators:
    build:
      context: .
      dockerfile: emulators/Dockerfile
    env_file: emulators/.env
    volumes:
      - ./emulators/data:/firebase/baseline-data
      - ./functions:/firebase/functions
      - ./extensions/:/firebase/extensions
      - ./.firebaserc:/firebase/.firebaserc
      - ./firebase.json:/firebase/firebase.json
      - ./firestore.indexes.json:/firebase/firebase.indexes.json
      - ./firestore.rules:/firebase/firestore.rules
      - ./storage.rules:/firebase/storage.rules
    ports:
      - 9099:9099
      - 5001:5001
      - 8080:8080
      - 9199:9199
      - 4000:4000
