version: "3"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/opt/jacobianmatthews.com/frontend
      - /opt/jacobianmatthews.com/frontend/node_modules
    environment:
      - PORT=3000
      - NODE_ENV=development
      - FIREBASE_AUTH_EMULATOR_HOST=http://emulators:9099
      - FIREBASE_PROJECT_ID=jacobianmatthews-com
      - BACKEND_URL=http://backend:3001
    ports:
      - 3000:3000
    depends_on:
      - backend
      - emulators

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: dev
    volumes:
      - ./backend:/src/jacobianmatthews.com/backend
      - ./backend/key.json:/run/secrets/google-service-account.json
    environment:
      - PORT=3001
      - DB_CONNECTION_STRING=postgres://backend:password@db/backend?sslmode=verify-full
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/google-service-account.json
    ports:
      - 3001:3001
    depends_on:
      - emulators
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=backend
    volumes:
      - ./db/data:/var/lib/postgresql/data

  emulators:
    build:
      context: .
      dockerfile: emulators/Dockerfile
    env_file: emulators/.env
    volumes:
      - ./emulators/data:/firebase/baseline-data
      - ./functions:/firebase/functions
      - ./extensions/:/firebase/extensions
      - ./.firebaserc:/firebase/.firebaserc
      - ./firebase.json:/firebase/firebase.json
      - ./firestore.indexes.json:/firebase/firebase.indexes.json
      - ./firestore.rules:/firebase/firestore.rules
      - ./storage.rules:/firebase/storage.rules
    ports:
      - 9099:9099
      - 5001:5001
      - 8080:8080
      - 9199:9199
      - 4000:4000
